# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Tbc.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setWindowTitle("User Auth")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setStyleSheet("QWidget {\n"
"    background-color: rgba(0, 0, 0, 190);\n"
"}\n"
"QLabel {\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"}\n"
"QPushButton#LogIn_but{    \n"
"    background-color: rgba(20, 47, 78, 219);\n"
"    color:rgba(255, 255, 255, 210);\n"
"    border-radius:9px;\n"
"}\n"
"QPushButton#LogIn_but:hover{    \n"
"    background-color: rgba(20, 47, 78, 219);\n"
"}\n"
"QPushButton#LogIn_but:pressed{    \n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(105, 118, 132, 200);\n"
"}QPushButton#RegisterPage_but{    \n"
"    background-color: rgba(20, 47, 78, 219);\n"
"    color:rgba(255, 255, 255, 210);\n"
"    border-radius:9px;\n"
"}\n"
"QPushButton#RegisterPage_but:hover{    \n"
"    background-color: rgba(20, 47, 78, 219);\n"
"}\n"
"QPushButton#RegisterPage_but:pressed{    \n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(105, 118, 132, 200);\n"
"}\n"
"QLineEdit{ \n"
"    background-color:rgba(0, 0, 0, 0);\n"
"    border:none;\n"
"    border-bottom:2px solid rgba(105, 118, 132, 255);\n"
"    color:rgba(255, 255, 255, 230);\n"
"    padding-left:7px;\n"
"}")
        self.stackedWidget.setObjectName("stackedWidget")
        self.Login_Page = QtWidgets.QWidget()
        self.Login_Page.setObjectName("Login_Page")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.Login_Page)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Username_LineEdit = QtWidgets.QLineEdit(self.Login_Page)
        self.Username_LineEdit.setMinimumSize(QtCore.QSize(250, 30))
        self.Username_LineEdit.setMaximumSize(QtCore.QSize(280, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Username_LineEdit.setFont(font)
        self.Username_LineEdit.setObjectName("Username_LineEdit")
        self.gridLayout_2.addWidget(self.Username_LineEdit, 3, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 10000, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 0, 2, 1, 1)
        self.Password_LineEdit = QtWidgets.QLineEdit(self.Login_Page)
        self.Password_LineEdit.setMinimumSize(QtCore.QSize(250, 30))
        self.Password_LineEdit.setMaximumSize(QtCore.QSize(280, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.Password_LineEdit.setFont(font)
        self.Password_LineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Password_LineEdit.setObjectName("Password_LineEdit")
        self.gridLayout_2.addWidget(self.Password_LineEdit, 5, 2, 1, 1)
        self.UserIcon_lbl = QtWidgets.QLabel(self.Login_Page)
        self.UserIcon_lbl.setMinimumSize(QtCore.QSize(30, 30))
        self.UserIcon_lbl.setMaximumSize(QtCore.QSize(35, 35))
        self.UserIcon_lbl.setStyleSheet("background-color:rgba(0, 0, 0, 120);\n"
"border:2px solid rgba(105, 118, 132, 255);\n"
"color:rgba(255, 255, 255, 230);\n"
"")
        self.UserIcon_lbl.setText("")
        self.UserIcon_lbl.setPixmap(QtGui.QPixmap("Assets\\Person.png"))
        self.UserIcon_lbl.setScaledContents(True)
        self.UserIcon_lbl.setIndent(0)
        self.UserIcon_lbl.setObjectName("UserIcon_lbl")
        self.gridLayout_2.addWidget(self.UserIcon_lbl, 3, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(10000, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 3, 0, 1, 1)
        self.LogInMain_lbl = QtWidgets.QLabel(self.Login_Page)
        self.LogInMain_lbl.setMinimumSize(QtCore.QSize(280, 40))
        self.LogInMain_lbl.setMaximumSize(QtCore.QSize(315, 45))
        font = QtGui.QFont()
        font.setFamily("MS UI Gothic")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.LogInMain_lbl.setFont(font)
        self.LogInMain_lbl.setStyleSheet("color:rgba(255, 255, 255, 210);")
        self.LogInMain_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.LogInMain_lbl.setObjectName("LogInMain_lbl")
        self.gridLayout_2.addWidget(self.LogInMain_lbl, 1, 1, 1, 2)
        self.LogIn_but = QtWidgets.QPushButton(self.Login_Page)
        self.LogIn_but.setMinimumSize(QtCore.QSize(280, 40))
        self.LogIn_but.setMaximumSize(QtCore.QSize(315, 45))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.LogIn_but.setFont(font)
        self.LogIn_but.setStyleSheet("")
        self.LogIn_but.setObjectName("LogIn_but")
        self.gridLayout_2.addWidget(self.LogIn_but, 10, 1, 1, 2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10000, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 12, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(10000, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 3, 3, 1, 1)
        self.PasswordIcon_lbl = QtWidgets.QLabel(self.Login_Page)
        self.PasswordIcon_lbl.setMinimumSize(QtCore.QSize(30, 30))
        self.PasswordIcon_lbl.setMaximumSize(QtCore.QSize(35, 35))
        self.PasswordIcon_lbl.setStyleSheet("background-color:rgba(0, 0, 0, 120);\n"
"border:2px solid rgba(105, 118, 132, 255);\n"
"color:rgba(255, 255, 255, 230);\n"
"")
        self.PasswordIcon_lbl.setText("")
        self.PasswordIcon_lbl.setPixmap(QtGui.QPixmap("Assets\\Lock.png"))
        self.PasswordIcon_lbl.setScaledContents(True)
        self.PasswordIcon_lbl.setObjectName("PasswordIcon_lbl")
        self.gridLayout_2.addWidget(self.PasswordIcon_lbl, 5, 1, 1, 1)
        self.Register_but = QtWidgets.QPushButton(self.Login_Page)
        self.Register_but.setMinimumSize(QtCore.QSize(280, 25))
        self.Register_but.setMaximumSize(QtCore.QSize(315, 30))
        self.Register_but.setStyleSheet("QPushButton {\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"    border: none;\n"
"    color: rgba(0, 150, 255, 210);\n"
"    padding-top: 10px;\n"
"    text-align: center;\n"
"}         \n"
"QPushButton:hover {\n"
"    text-decoration: underline;\n"
"}")
        self.Register_but.setObjectName("Register_but")
        self.gridLayout_2.addWidget(self.Register_but, 11, 1, 1, 2)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 9, 1, 1, 2)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 6, 1, 1, 2)
        self.Error_lbl = QtWidgets.QLabel(self.Login_Page)
        self.Error_lbl.setMinimumSize(QtCore.QSize(280, 15))
        self.Error_lbl.setMaximumSize(QtCore.QSize(315, 18))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Error_lbl.setFont(font)
        self.Error_lbl.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Error_lbl.setStyleSheet("color:rgba(255, 0, 0, 140);")
        self.Error_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.Error_lbl.setObjectName("Error_lbl")
        self.gridLayout_2.addWidget(self.Error_lbl, 7, 1, 1, 2)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 4, 1, 1, 2)
        spacerItem7 = QtWidgets.QSpacerItem(40, 60, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem7, 2, 1, 1, 2)
        self.stackedWidget.addWidget(self.Login_Page)
        self.Register_Page = QtWidgets.QWidget()
        self.Register_Page.setObjectName("Register_Page")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.Register_Page)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.ErrorPassword_lbl = QtWidgets.QLabel(self.Register_Page)
        self.ErrorPassword_lbl.setMinimumSize(QtCore.QSize(250, 30))
        self.ErrorPassword_lbl.setMaximumSize(QtCore.QSize(315, 35))
        self.ErrorPassword_lbl.setStyleSheet("color:rgba(255, 0, 0, 140);")
        self.ErrorPassword_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.ErrorPassword_lbl.setObjectName("ErrorPassword_lbl")
        self.gridLayout_3.addWidget(self.ErrorPassword_lbl, 10, 1, 1, 2)
        spacerItem8 = QtWidgets.QSpacerItem(247, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem8, 11, 1, 1, 2)
        spacerItem9 = QtWidgets.QSpacerItem(769, 60, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem9, 2, 1, 1, 2)
        spacerItem10 = QtWidgets.QSpacerItem(804, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem10, 4, 2, 1, 1)
        self.LogInMain_lbl_2 = QtWidgets.QLabel(self.Register_Page)
        self.LogInMain_lbl_2.setMinimumSize(QtCore.QSize(280, 40))
        self.LogInMain_lbl_2.setMaximumSize(QtCore.QSize(315, 45))
        font = QtGui.QFont()
        font.setFamily("MS UI Gothic")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.LogInMain_lbl_2.setFont(font)
        self.LogInMain_lbl_2.setStyleSheet("color:rgba(255, 255, 255, 210);")
        self.LogInMain_lbl_2.setAlignment(QtCore.Qt.AlignCenter)
        self.LogInMain_lbl_2.setObjectName("LogInMain_lbl_2")
        self.gridLayout_3.addWidget(self.LogInMain_lbl_2, 1, 1, 1, 2)
        self.Username_LineEdit_2 = QtWidgets.QLineEdit(self.Register_Page)
        self.Username_LineEdit_2.setMinimumSize(QtCore.QSize(250, 30))
        self.Username_LineEdit_2.setMaximumSize(QtCore.QSize(280, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Username_LineEdit_2.setFont(font)
        self.Username_LineEdit_2.setObjectName("Username_LineEdit_2")
        self.gridLayout_3.addWidget(self.Username_LineEdit_2, 3, 2, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(10000, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem11, 5, 0, 1, 1)
        self.PasswordIcon_lbl_2 = QtWidgets.QLabel(self.Register_Page)
        self.PasswordIcon_lbl_2.setMinimumSize(QtCore.QSize(30, 30))
        self.PasswordIcon_lbl_2.setMaximumSize(QtCore.QSize(35, 35))
        self.PasswordIcon_lbl_2.setStyleSheet("background-color:rgba(0, 0, 0, 120);\n"
"border:2px solid rgba(105, 118, 132, 255);\n"
"color:rgba(255, 255, 255, 230);\n"
"")
        self.PasswordIcon_lbl_2.setText("")
        self.PasswordIcon_lbl_2.setPixmap(QtGui.QPixmap("Assets\\Lock.png"))
        self.PasswordIcon_lbl_2.setScaledContents(True)
        self.PasswordIcon_lbl_2.setObjectName("PasswordIcon_lbl_2")
        self.gridLayout_3.addWidget(self.PasswordIcon_lbl_2, 5, 1, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 10000, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem12, 0, 2, 1, 1)
        self.UserIcon_lbl_2 = QtWidgets.QLabel(self.Register_Page)
        self.UserIcon_lbl_2.setMinimumSize(QtCore.QSize(30, 30))
        self.UserIcon_lbl_2.setMaximumSize(QtCore.QSize(35, 35))
        self.UserIcon_lbl_2.setStyleSheet("background-color:rgba(0, 0, 0, 120);\n"
"border:2px solid rgba(105, 118, 132, 255);\n"
"color:rgba(255, 255, 255, 230);\n"
"")
        self.UserIcon_lbl_2.setText("")
        self.UserIcon_lbl_2.setPixmap(QtGui.QPixmap("Assets\\Person.png"))
        self.UserIcon_lbl_2.setScaledContents(True)
        self.UserIcon_lbl_2.setIndent(0)
        self.UserIcon_lbl_2.setObjectName("UserIcon_lbl_2")
        self.gridLayout_3.addWidget(self.UserIcon_lbl_2, 3, 1, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(247, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem13, 6, 2, 1, 1)
        self.RegisterPage_but = QtWidgets.QPushButton(self.Register_Page)
        self.RegisterPage_but.setMinimumSize(QtCore.QSize(280, 40))
        self.RegisterPage_but.setMaximumSize(QtCore.QSize(315, 45))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.RegisterPage_but.setFont(font)
        self.RegisterPage_but.setStyleSheet("")
        self.RegisterPage_but.setObjectName("RegisterPage_but")
        self.gridLayout_3.addWidget(self.RegisterPage_but, 12, 1, 1, 2)
        self.Password_LineEdit_2 = QtWidgets.QLineEdit(self.Register_Page)
        self.Password_LineEdit_2.setMinimumSize(QtCore.QSize(250, 30))
        self.Password_LineEdit_2.setMaximumSize(QtCore.QSize(280, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.Password_LineEdit_2.setFont(font)
        self.Password_LineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Password_LineEdit_2.setObjectName("Password_LineEdit_2")
        self.gridLayout_3.addWidget(self.Password_LineEdit_2, 5, 2, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(20, 10000, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem14, 14, 2, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(10000, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem15, 5, 3, 1, 1)
        self.Password_LineEdit_3 = QtWidgets.QLineEdit(self.Register_Page)
        self.Password_LineEdit_3.setMinimumSize(QtCore.QSize(250, 30))
        self.Password_LineEdit_3.setMaximumSize(QtCore.QSize(280, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.Password_LineEdit_3.setFont(font)
        self.Password_LineEdit_3.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Password_LineEdit_3.setObjectName("Password_LineEdit_3")
        self.gridLayout_3.addWidget(self.Password_LineEdit_3, 7, 2, 1, 1)
        self.PasswordIcon_lbl_3 = QtWidgets.QLabel(self.Register_Page)
        self.PasswordIcon_lbl_3.setMinimumSize(QtCore.QSize(30, 30))
        self.PasswordIcon_lbl_3.setMaximumSize(QtCore.QSize(35, 35))
        self.PasswordIcon_lbl_3.setStyleSheet("background-color:rgba(0, 0, 0, 120);\n"
"border:2px solid rgba(105, 118, 132, 255);\n"
"color:rgba(255, 255, 255, 230);\n"
"")
        self.PasswordIcon_lbl_3.setText("")
        self.PasswordIcon_lbl_3.setPixmap(QtGui.QPixmap("Assets\\Lock.png"))
        self.PasswordIcon_lbl_3.setScaledContents(True)
        self.PasswordIcon_lbl_3.setObjectName("PasswordIcon_lbl_3")
        self.gridLayout_3.addWidget(self.PasswordIcon_lbl_3, 7, 1, 1, 1)
        self.BackToLogin_but = QtWidgets.QPushButton(self.Register_Page)
        self.BackToLogin_but.setStyleSheet("QPushButton {\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"    border: none;\n"
"    color: rgba(0, 150, 255, 210);\n"
"    padding-top: 10px;\n"
"    text-align: center;\n"
"}         \n"
"QPushButton:hover {\n"
"    text-decoration: underline;\n"
"}")
        self.BackToLogin_but.setObjectName("BackToLogin_but")
        self.gridLayout_3.addWidget(self.BackToLogin_but, 13, 1, 1, 2)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem16, 9, 1, 1, 2)
        self.stackedWidget.addWidget(self.Register_Page)
        self.Main_Page = QtWidgets.QWidget()
        self.Main_Page.setObjectName("Main_Page")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.Main_Page)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem17 = QtWidgets.QSpacerItem(20, 181, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem17, 4, 1, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(337, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem18, 3, 2, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(337, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem19, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.Main_Page)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("Assets\\Person.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 1, 1, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(337, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem20, 3, 0, 1, 1)
        spacerItem21 = QtWidgets.QSpacerItem(20, 181, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem21, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.Main_Page)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setStyleSheet("color:rgba(105, 118, 132, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 3, 1, 1, 1)
        spacerItem22 = QtWidgets.QSpacerItem(337, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem22, 2, 2, 1, 1)
        self.stackedWidget.addWidget(self.Main_Page)
        self.gridLayout.addWidget(self.stackedWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)


        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Username_LineEdit.setPlaceholderText(_translate("MainWindow", "Username"))
        self.Password_LineEdit.setPlaceholderText(_translate("MainWindow", "Password"))
        self.LogInMain_lbl.setText(_translate("MainWindow", "Login"))
        self.LogIn_but.setText(_translate("MainWindow", "Login"))
        self.Register_but.setText(_translate("MainWindow", "Create a new account"))
        self.Error_lbl.setText(_translate("MainWindow", ""))
        self.ErrorPassword_lbl.setText(_translate("MainWindow", ""))
        self.LogInMain_lbl_2.setText(_translate("MainWindow", "Registration"))
        self.Username_LineEdit_2.setPlaceholderText(_translate("MainWindow", "Username"))
        self.RegisterPage_but.setText(_translate("MainWindow", "Register"))
        self.Password_LineEdit_2.setPlaceholderText(_translate("MainWindow", "Password"))
        self.Password_LineEdit_3.setPlaceholderText(_translate("MainWindow", "Password"))
        self.BackToLogin_but.setText(_translate("MainWindow", "Back to Login"))
        self.label.setText(_translate("MainWindow", "Welcome back {Username}"))

